;M7 CORE!
[env:portenta_h7_m7]
platform = ststm32
board = portenta_h7_m7
framework = arduino

upload_protocol = custom
upload_flags =
    -f
    /home/gr-towr/Documents/GR-LRR_Firmware/openocd-portenta-pi.cfg
    -c
    program {$SOURCE} verify reset; shutdown

upload_command = /home/gr-towr/opt/openocd-dev/bin/openocd -f /home/gr-towr/Documents/Test/openocd-portenta-pi.cfg -c "init; reset halt; program /home/gr-towr/Documents/GR-LRR_Firmware/.pio/build/portenta_h7_m7/firmware.elf verify reset; shutdown"

monitor_port = /dev/ttyAMA0
monitor_speed = 115200
build_unflags =
  -mfloat-abi=soft

build_flags =
  -Wall
  -g
  -mfloat-abi=softfp

platform_packages =
  toolchain-gccarmnoneeabi

lib_deps = 
    ;khoih-prog/WebSockets2_Generic@^1.13.2
    khoih-prog/Portenta_H7_TimerInterrupt@^1.4.0
    khoih-prog/Portenta_H7_PWM @ ^2.1.0

    ;Functional-Vlpp
    ;DoubleResetDetector_Generic
	bblanchon/ArduinoJson@^6.21.3 
  adafruit/Adafruit MCP4728@^1.0.0
  adafruit/Adafruit ADS1x15@^2.2.0
  adafruit/Adafruit BusIO@^1.9.3
  adafruit/Adafruit NeoPixel@^1.11.0
  duinoWitchery/hd44780
  adafruit/Adafruit GFX Library@^1.11.7
  adafruit/Adafruit SSD1306@^2.4.7
  arduino-libraries/Servo@^1.3.0


lib_ignore = 
    ; ArduinoJson
    ; DoubleResetDetector_Generic
    DueFlashStorage
    ESP_AT_Lib
    Ethernet_Generic
    EthernetENC
    EthernetWebServer
    EthernetWebServer_STM32
    FlashStorage_RTL8720
    FlashStorage_SAMD
    ; FlashStore_STM32
    FlashStore_STM32F1
    ; Functional-Vlpp
    QNEthernet
    SinricPro_Generic
    STM32duino LwIP
    STM32Ethernet
    UIPEthernet
    WebServer_WT32_ETH01
    ; WebSockets_Generic
    WiFi101
    WiFi101_Generic
    WiFiEspAT
    WiFiMulti_Generic
    WiFiNINA_Generic
    ; WifiWebServer